import Head from 'next/head'
import Script from 'next/script'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Maze Generation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <h1 className={styles.title}>Maze Generator</h1>
      <div className={styles.complete}>
        <h3>Maze Completed.</h3>
        <button className={styles.replay} idName={styles.submit}>Play again</button>
        <button className={styles.close} idName={styles.submit}>Close</button>
      </div>
      <canvas className={styles.maze}></canvas>
      <Script src='maze.js'/>
    </div>
  )
}
